name: Continuous Integration
permissions: read-all

on:
  pull_request:
    branches:
      - main
      - devs/**

jobs:
  linters:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4.1.7

      - name: Setup Python 🔧
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.12.5

      - name: Download actionlint
        id: get_actionlint
        # yamllint disable-line rule:line-length
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.7.1

      - name: Test 🔍
        run: |
          # nosemgrep: generic.ci.security.use-frozen-lockfile.use-frozen-lockfile-pip
          pip install semgrep yamllint
          semgrep --config=auto --error
          yamllint .
          ${{ steps.get_actionlint.outputs.executable }} -color

  validate_orb:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4.1.7

      - name: Install CircleCI CLI
        run: curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/main/install.sh | bash

      - name: Validate Orb
        run: |
          circleci orb pack src > orb.yml
          circleci orb validate orb.yml

#  test_script:
#    timeout-minutes: 5
#    runs-on: ubuntu-22.04
#    steps:
#      - name: Checkout 🛎️
#        uses: actions/checkout@v4.1.7
#
#      - name: Setup Python 🔧
#        uses: actions/setup-python@v5.1.1
#        with:
#          python-version: 3.12.5
#
#      - name: Install Python dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install pytest
#
#      - name: Run tests
#        run: |
#          pytest
